query MainCategories {
  mainCategories {
    id
    title_us
    title_tr
    title_cn
    title_es
    categories {
      id
      name_us
      name_tr
      name_cn
      name_es
      image {
        url
      }
    }
  }
}
