query ArticleTrs {
  articleTrs {
    id
    title
    content
    image {
      url
    }
    category_tr {
      id
      name
    }
    publised_at
    next_article {
      id
      title
    }
    previous_article {
      id
      title
    }
    author {
      id
      author_name
      author_avatar {
        url
      }
      author_profile
    }
  }
}
