query Category($id: ID!) {
  categoryTr(id: $id) {
    name
    article_trs {
      id
      title
      content
      publised_at
      image {
        url
      }
      category_tr {
        id
        name
      }
      next_article {
        id
        title
      }
      previous_article {
        id
        title
      }
    }
  }
}
